#!/usr/bin/env bash

PLUGIN=$1
PLUGIN_DIRECTORY=$2

echo "Downloading extension..."
wget -O /tmp/extension.zip "${PLUGIN}" > /dev/null

unzip /tmp/extension.zip -d /tmp/extension

mv /tmp/extension/extension ${VSCODE_EXT_DIRECTORY}/${PLUGIN_DIRECTORY}

# Cleanup
echo "Cleaning up..."
rm -rf /tmp/extension.zip /tmp/extension